# Generated by Django 2.2.1 on 2019-06-09 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=models.CharField(max_length=200, verbose_name='نام رویداد'), max_length=200, verbose_name='مکان'),
        ),
        migrations.AlterField(
            model_name='event',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت'),
        ),
        migrations.AlterField(
            model_name='event',
            name='last_modified',
            field=models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر'),
        ),
    ]
