# Generated by Django 2.2.1 on 2019-06-10 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20190610_0404'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('date',)},
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام و نام خانوادگی')),
                ('tell', models.CharField(max_length=13, verbose_name='شماره موبایل')),
                ('address', models.CharField(blank=True, max_length=300)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('event', models.ManyToManyField(to='event.Event', verbose_name='رویداد مورد نظر')),
            ],
            options={
                'ordering': ('last_modified',),
            },
        ),
    ]
