# Generated by Django 2.2.1 on 2019-06-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20190610_0430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(blank=True, max_length=300, verbose_name='آدرس'),
        ),
    ]
