# Generated by Django 2.2.1 on 2019-06-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20190610_0510'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='price',
            field=models.CharField(default='رایگان', max_length=100, verbose_name='هزینه ثبت نام'),
        ),
    ]
