# Generated by Django 2.2.1 on 2019-06-10 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_event_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='desc',
            field=models.TextField(blank=True, verbose_name='توضیحات اضافه'),
        ),
    ]
