# Generated by Django 2.2.1 on 2019-06-10 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_user_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='پست الکترونیک'),
        ),
    ]
