# Generated by Django 2.2.1 on 2019-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_user_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('-last_modified',)},
        ),
        migrations.AddField(
            model_name='event',
            name='pic',
            field=models.ImageField(blank=True, max_length=500, upload_to='files/images/events/', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=25, verbose_name='سن'),
        ),
        migrations.AlterField(
            model_name='user',
            name='event',
            field=models.ManyToManyField(to='event.Event', verbose_name='رویداد ها'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tell',
            field=models.CharField(max_length=13, verbose_name='شماره تلفن همراه'),
        ),
    ]
