# Generated by Django 2.2.1 on 2019-06-11 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0009_auto_20190611_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(verbose_name='سن'),
        ),
    ]
