# Generated by Django 2.2.1 on 2019-06-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_auto_20190611_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pic',
            field=models.ImageField(blank=True, max_length=500, upload_to='./static/event/', verbose_name='تصویر'),
        ),
    ]
