# Generated by Django 2.2.1 on 2019-06-11 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0011_auto_20190611_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pic',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='media/', verbose_name='تصویر'),
        ),
    ]
