# Generated by Django 2.2.1 on 2019-06-12 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0014_auto_20190611_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='picv',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='event/', verbose_name='تصویر-عمودی'),
        ),
    ]
