# Generated by Django 2.2.1 on 2019-06-12 02:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0015_event_picv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='pic',
            field=models.ImageField(default=datetime.datetime(2019, 6, 12, 2, 21, 13, 88397, tzinfo=utc), max_length=500, upload_to='event/', verbose_name='تصویر'),
            preserve_default=False,
        ),
    ]
