# Generated by Django 2.2.1 on 2019-06-13 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0016_auto_20190612_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='lat',
            field=models.FloatField(blank=True, default=0, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AddField(
            model_name='event',
            name='lng',
            field=models.FloatField(blank=True, default=0, verbose_name='طول جغرافیایی'),
        ),
    ]
