# Generated by Django 2.2.1 on 2019-06-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0017_auto_20190613_0450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.FloatField(blank=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lng',
            field=models.FloatField(blank=True, verbose_name='طول جغرافیایی'),
        ),
    ]
