# Generated by Django 2.2.1 on 2019-06-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0018_auto_20190613_0451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='duration',
            field=models.IntegerField(default=1, verbose_name='مدت/ روز'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='عرض جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='event',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='طول جغرافیایی'),
        ),
        migrations.AlterField(
            model_name='event',
            name='price',
            field=models.CharField(default='رایگان', max_length=100, verbose_name='هزینه ثبت نام/ تومان'),
        ),
    ]
