# Generated by Django 2.2.1 on 2019-06-17 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0019_auto_20190616_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_fa',
            field=models.CharField(default='آخر این هفته', max_length=100, verbose_name='تاریخ فارسی'),
        ),
    ]
